name: Generate Standards

on:
  workflow_dispatch:

jobs:
  fetch-pr-diff-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('bin/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bin/requirements.txt

      - name: Generate Standards
        run: |
          cd bin
          python best_practices.py
        env:
          GITHUB_TOKEN: ${{ secrets.BANKRATE_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPO: ${{ github.repository }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Update Red Rover Best Practices"
          body: "This PR updates the red_rover_standards.txt file using the bin/best_practices.py script."
          branch: red-rover-standards-update
