name: Fetch PR diff urls

on:
  workflow_dispatch:

jobs:
  fetch-pr-diff-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch PR diff urls
      run: |
        import requests

        owner = "bankrate"
        repo = "ai-editorial-platform-service"
        github_token = '${{ secrets.GITHUB_TOKEN }}'

        base_url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

        headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json",
        }

        diff_urls = []

        response = requests.get(base_url, headers=headers, params={'state': 'all', 'per_page': 10})

        if response.status_code == 200:
            pull_requests = response.json()
            for pr in pull_requests:
                diff_url = pr['diff_url']
                diff_urls.append(diff_url)
        else:
            print(f"Failed to fetch pull requests: {response.status_code}, {response.text}")
      shell: python
