name: RedRover Generate Standards

on:
  workflow_dispatch:

jobs:
  fetch-pr-diff-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('red_rover/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r red_rover/requirements.txt

      - name: Generate Standards
        run: python red_rover/generate_standards.py
        env:
          GITHUB_TOKEN: ${{ secrets.BANKRATE_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPO: ${{ github.repository }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Update Red Rover standards specific to this repo"
          body: "This PR updates the red_rover/custom_prompt.txt file using the red_rover/generate_standards.py script."
          branch: red-rover-standards-update

      - name: Post Pull Request URL
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
