name: RedRover Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read file
        id: file
        run: echo "::set-output name=content::$(cat red_rover/custom_prompt.txt)"
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.BANKRATE_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }} # Uncomment if using Anthropic
        with:
          model_provider: openai # or 'anthropic'
          light_model: gpt-4.1-mini # or 'claude-3-5-haiku-20241022'
          heavy_model: gpt-4.1 # or 'o4-mini', 'claude-sonnet-4-20250514'
          review_simple_changes: false
          less_verbose_review: false
          review_comment_lgtm: false
          poem_enabled: false
          debug: false
          path_filters: |
            !dist/**
            !**/*.lock
          system_message: ${{ steps.file.outputs.content }}   
